# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlockOneNewProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlockOneNewProject

pod 'Alamofire', '~> 5.5'
pod 'SwiftLint'

# Firebase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'

end
